### ISSUE TITLE
Opening Laptop shade Animation is not loading.

### ISSUE THREAD

**Issue by genze121** [Anmol-Baranwal/Cool-GIFs-For-Readme#11]

**Comment by genze121** [comment]
This gif for opening a laptop shade animation can help:-

<img src="https://cdn.dribbble.com/users/2057155/screenshots/4542166/laptop.gif" alt="Opening Laptop" />

**Comment by Anmol-Baranwal** [comment]
I removed it, don't really know why access was denied. Closing this issue.
