### ISSUE TITLE
[Add] New avatar for Github 

### ISSUE THREAD

**Issue by singodiyashubham87** [Anmol-Baranwal/Cool-GIFs-For-Readme#2]
I want to add a new avatar for Github
![image](https://github.com/Anmol-Baranwal/Cool-GIFs-For-GitHub/assets/93720428/81bdcb88-9ca4-448c-8637-bd82ab0ddabc)

**Comment by Anmol-Baranwal** [comment]
Hi @singodiyashubham87,

I'm sorry, but I'm not currently accepting any pull requests (PRs) or issues for this. I will close the tab accordingly. There are already many GIFs available, and I'm only adding the ones that I find useful.

There can be hundreds of PRs for adding a avatar which isn't practical, and it wouldn't even give credibility.

I hope you understand. I'm going to close this now!
