### ISSUE TITLE
Copyright / Licensing for sourced images

### ISSUE THREAD

**Issue by tomek-i** [Anmol-Baranwal/Cool-GIFs-For-Readme#5]
I assume that none of those images were created by you and you sourced them somewhere. 

You really should add the source of the images and credit the artists.
You should also consider if you're violating potential copyrights here by distributing the images without licence / author information and or permission. 

The coding Mario is coming from https://radio.x-team.com/ not sure if thats the source and or if they hold the right to the art.

**Comment by Anmol-Baranwal** [comment]
Hi @tomek-i 
Yes, I'm aware of copyrights.

However, I've actually sourced them from README profiles that had appropriate licenses. Some might be from Giphy, which is permissible for personal and non-commercial purposes, such as on GitHub.

It's challenging to determine the actual source. Specifically, I don't believe it's an issue to use them in README files, and I'm willing to remove any if someone ever reaches out.

**Comment by Anmol-Baranwal** [comment]
I'm closing this if you have no further questions, feel free to reopen it if you want to ask something.
