### ISSUE TITLE
js

### ISSUE THREAD

**Issue by adeep777** [Anmol-Baranwal/Cool-GIFs-For-Readme#6]
![JS](https://user-images.githubusercontent.com/74038190/212257454-16e3712e-945a-4ca2-b238-408ad0bf87e6.gif)

**Comment by Anmol-Baranwal** [comment]
Hi @adeep777 
It's already in the repo. What is this issue for?

**Comment by adeep777** [comment]
It was just an accident,I am sorry.

**Comment by Anmol-Baranwal** [comment]
No worries, I'm closing it.
