### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Bashamega** [Anmol-Baranwal/Cool-GIFs-For-Readme#7]
Hello Anmol:)

I think this repo is cool and more people should know it.
I was thinking of contributing by creating a pure HTML website for this repo so that people can find it on search engines.
I was think of using [docsify ](https://docsify.js.org/)and I think it will look great.

**Comment by Anmol-Baranwal** [comment]
> Hello Anmol:)
> 
> I think this repo is cool and more people should know it. I was thinking of contributing by creating a pure HTML website for this repo so that people can find it on search engines. I was think of using [docsify ](https://docsify.js.org/)and I think it will look great.

Thanks @Bashamega! It seems like an awesome idea. 
It's already visible, but let me do a bit of research, and I'll let you know if it's necessary. 
My original idea was to keep it just in the markdown.

**Comment by Bashamega** [comment]
> > Hello Anmol:)
> > I think this repo is cool and more people should know it. I was thinking of contributing by creating a pure HTML website for this repo so that people can find it on search engines. I was think of using [docsify ](https://docsify.js.org/)and I think it will look great.
> 
> Thanks @Bashamega! It seems like an awesome idea. It's already visible, but let me do a bit of research, and I'll let you know if it's necessary. My original idea was to keep it just in the markdown.

Ok:) 
Take your time. Also, if you want i can create it as a separate repo on my account if you don't want it to be on this repo. But i think it really deserves to have a place on the web <3

**Comment by Anmol-Baranwal** [comment]
@Bashamega 
To be honest, I'm still unsure whether I should proceed with it or not, especially considering that it might not be very useful since it's just GIFs on the web.

But let's give it a try. Please make a PR, and I will review the changes.

It feels very different to use semantic versioning with such a repo!
