### ISSUE TITLE
gif

### ISSUE THREAD

**Issue by wicaksonosetyo** [Anmol-Baranwal/Cool-GIFs-For-Readme#9]
![stiker cute](https://github.com/user-attachments/assets/a975f07b-6d93-4e98-96a0-69a75b8530f2)

**Comment by Anmol-Baranwal** [comment]
I’ve stopped adding any more for now but will include them in the next commit in a few days.

**Comment by Anmol-Baranwal** [comment]
I've added it with the latest commit. closing this issue.
